version: "3.7"

services:
  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - type: bind
        source: ./logs
        target: ${POSTGRES_LOG_DIRECTORY}
    command: bash -c "chmod 777 ${POSTGRES_LOG_DIRECTORY} &&
      /docker-entrypoint.sh postgres -c log_statement='all'
      -c log_directory=${POSTGRES_LOG_DIRECTORY}
      -c logging_collector=on"
    ports:
      - "5432:5432"
